name: CD to VPS (minimal)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Compute tags
        id: vars
        run: |
          echo "SHA_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (Optional) Inject commit SHA into page
        run: |
          sed -i "s/__COMMIT_SHA__/${{ steps.vars.outputs.SHA_TAG }}/" web/index.html

      - name: Build & Push web image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.REPO_NAME }}-web:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.REPO_NAME }}-web:${{ steps.vars.outputs.SHA_TAG }}

  deploy_to_vps:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v4
      - name: Compute tags
        id: vars
        run: |
          echo "SHA_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Copy compose & deploy script to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml,ops/deploy.sh"
          target: "~/mini-cicd"

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/mini-cicd
            chmod +x ops/deploy.sh
            OWNER="${{ secrets.OWNER }}" \
            SHA_TAG="${{ steps.vars.outputs.SHA_TAG }}" \
            REGISTRY="ghcr.io" \
            REPO_NAME="${{ steps.vars.outputs.REPO_NAME }}" \
            bash ops/deploy.sh

